In [ ]:
## find cases that are hits according to Turbo eval but non-inferables according to 4.1

In [7]:
import pandas as pd
import re

In [2]:
eval41 = pd.read_csv('41eval-GPT41Prod.csv', index_col = 0)

In [3]:
evalturbo = pd.read_csv('GPT41ProdDiagandEval.csv', index_col = 0)

In [4]:
def analyze_results(text, index):
    mistakes = []
    hits = []
    excluded = [] #not a medical diagnosis
    noninferables = []
    current = 1
    total_adjust = 0
    #for conditions that GPT-4 grouped together - still doesn't capture issue with hadmid 23707730
    from_nums = []
    to_nums = []
    grouped = re.findall(r'\n\d+-\d+:', text)
    if len(grouped) > 0:
        #print("Grouping found!")
        #print("At index: ")
        #print(index)
        for elem in grouped:
            from_nums.append(str(int(elem.split('-')[0]))) #str(int()) for safety
            to_nums.append(str(int(elem.split('-')[1].strip(':'))))
    while 1:
        try:
            if current == 1:
                number = str(current)
                #sometimes GPT-4 adds words like Diagnosis or Actual diagnosis, and we want to capture that
                pre_word = text.split(number, 1)[0]
            #for conditions that GPT-4 grouped together
            elif str(current) in from_nums:
                idx = from_nums.index(str(current))
                number = grouped[idx]
                total_adjust += int(to_nums[idx]) - current
                current = int(to_nums[idx])
            else:
                number = '\n' + pre_word + str(current)
            nextOne = '\n' + pre_word + str(current+1)
            if text.split(number, 1)[1].split('Question 1: ', 1)[1][:2] == 'No':
                if 'not a medical diagnosis' in text.split(number, 1)[1].split('Question 1: ', 1)[1].split('Question 2: ', 1)[0].split(nextOne, 1)[0]:
                    print(index)
                    print(text.split(number, 1)[1].split('Question 1: ', 1)[0])
                    excluded.append(str(current))
                else:
                    hits.append(str(current))
            elif text.split(number, 1)[1].split('Question 2: ', 1)[1][:3] == 'Yes':
                mistakes.append(str(current))
            elif text.split(number, 1)[1].split('Question 2: ', 1)[1][:2] == 'No':
                noninferables.append(str(current))
            else:
                print("Unable to parse text when looking at diagnosis number: ")
                print(current)
                print("At index: ")
                print(index)
        except:
            #print('Diagnosis number not found in text: ')
            #print(current)
            total = current - 1 - total_adjust
            break
        current += 1
    return pd.Series([len(hits), len(noninferables), len(mistakes), len(excluded), '; '.join(hits), '; '.join(noninferables), '; '.join(mistakes), '; '.join(excluded), total])

In [5]:
def analysis(result_df):
  analyzed_df = result_df.apply(lambda row: analyze_results(row['GPT-Eval'], row.name),1)
  analyzed_df.columns = ['no_hits', 'no_noninferables', 'no_mistakes', 'no_excluded', 'hits', 'noninferables', 'mistakes', 'excluded', 'total_ICD_diagnoses']
  analyzed_df['error'] = analyzed_df['no_mistakes'] / (analyzed_df['no_hits'] + analyzed_df['no_mistakes'])
  analyzed_df['sensitivity'] = 1-analyzed_df['error']
  print(analyzed_df['sensitivity'].mean())
  print(1-(analyzed_df['no_mistakes'].sum() / (analyzed_df['no_hits'].sum() + analyzed_df['no_mistakes'].sum())))

  results = pd.concat([result_df, analyzed_df], axis=1)

  return results

In [8]:
eval41 = analysis(eval41)

6
: Encounter for examination for normal comparison and control in clinical research program

8
: Physical restraint status

14
: Unspecified place or not applicable

16
: Other place in single-family (private) house as the place of occurrence of the external cause

16
: Physical restraint status

16
: Family history of alcohol abuse and dependence

16
: Family history of other mental and behavioral disorders

16
: Exposure to other specified factors, initial encounter

16
: Unspecified place or not applicable

19
: Examination of participant in clinical trial

19
: Accidents occurring in residential institution

22
: Encounter for examination for normal comparison and control in clinical research program

24
: Other specified places as the place of occurrence of the external cause

28
: Encounter for immunization

34
: Encounter for palliative care

37
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

38
: Patient room in hospital as the place of occurrence of the external cause

45
: Other place in hospital as the place of occurrence of the external cause

46
: Lack of housing

47
: Other place in hospital as the place of occurrence of the external cause

50
: Do not resuscitate

50
: Encounter for immunization

52
: Operating room of hospital as the place of occurrence of the external cause

52
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

59
: Unspecified place in apartment as the place of occurrence of the external cause

62
: Fall from other slipping, tripping, or stumbling

62
: Activities involving walking an animal

63
: Encounter for immunization

72
: Unspecified place or not applicable

73
: Encounter for immunization

75
: Encounter for examination for normal comparison and control in clinical research program

76
: Unspecified place or not applicable

78
: Awaiting organ transplant status

80
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

85
: Examination of participant in clinical trial

88
: Examination of participant in clinical trial

91
: Amputation of limb(s) as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure

91
: Long term (current) use of insulin

91
: Unspecified place in hospital as the place of occurrence of the external cause

93
: Encounter for immunization

93
: Body mass index (BMI) 23.0-23.9, adult

96
: Encounter for immunization

102
: Examination of participant in clinical trial

104
: Do not resuscitate status

105
: Do not resuscitate status

105
: Encounter for palliative care

108
: Other dependence on machines, supplemental oxygen

108
: Do not resuscitate status

108
: Physical restraints status

109
: Homelessness

113
: Do not resuscitate status

116
: Unspecified place in hospital as the place of occurrence of the external cause

116
: Do not resuscitate

116
: Encounter for immunization

121
: Unspecified place or not applicable

122
: Fall on same level, unspecified, initial encounter

122
: History of falling

122
: Other specified places as the place of occurrence of the external cause

127
: Unspecified place in nursing home as the place of occurrence of the external cause

130
: Dependence on wheelchair

130
: Unspecified place in single-family (private) house as the place of occurrence of the external cause

137
: Do not resuscitate

137
: Long term (current) use of insulin

137
: Long term (current) use of anticoagulants

137
: Presence of automatic (implantable) cardiac defibrillator

138
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

144
: Examination of participant in clinical trial

151
: Encounter for immunisation

151
: Long term (current) use of aspirin

151
: Long term (current) use of anticoagulants

156
: Bathroom of single-family (private) house as the place of occurrence of the external cause

156
: Other place in single-family (private) house as the place of occurrence of the external cause

156
: Homelessness

158
: Unspecified fall, initial encounter

158
: Unspecified place in other non-institutional residence as the place of occurrence of the external cause

166
: Unspecified place in hospital as the place of occurrence of the external cause

166
: Radiological procedure and radiotherapy as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure

166
: Unspecified place or not applicable

168
: Encounter for immunization

172
: Exposure to other specified factors, initial encounter

172
: Unspecified place or not applicable

181
: Do not resuscitate

181
: Unspecified place or not applicable

185
: Do not resuscitate

190
: Knee joint replacement

194
: Do not resuscitate

194
: Dependence on wheelchair

194
: Unspecified place or not applicable

206
: Other specified places as the place of occurrence of the external cause

213
: Unspecified place in apartment as the place of occurrence of the external cause

219
: Physical restraint status

219
: Patient's other noncompliance with medication regimen

221
: Unspecified place or not applicable

221
: Long term (current) use of oral hypoglycemic drugs

221
: Fall on same level from slipping, tripping and stumbling without subsequent striking against object, initial encounter

222
: Do not resuscitate status

225
: Unspecified place in hospital as the place of occurrence of the external cause

227
: Encounter for immunization

227
: Presence of unspecified artificial knee joint

237
: Examination of participant in clinical trial

239
: Do not resuscitate

239
: Dependence on wheelchair

239
: Presence of right artificial hip joint

241
: Long-term (current) use of insulin

243
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

243
: Unspecified place in hospital as the place of occurrence of the external cause

249
: Unspecified place or not applicable

252
: Other place in hospital as the place of occurrence of the external cause

256
: Long term (current) use of antibiotics

256
: Long term (current) use of opiate analgesic

256
: Long term (current) use of anticoagulants

259
: Long-term (current) use of other medications

262
: Encounter for immunization

266
: Need for prophylactic vaccination and inoculation against influenza

268
: Unspecified place in hospital as the place of occurrence of the external cause

274
: Examination of participant in clinical trial

276
: Patient room in hospital as the place of occurrence of the external cause

277
: Examination of participant in clinical trial

278
: Do not resuscitate status

278
: Encounter for palliative care

282
: Allergy status to other drugs, medicaments and biological substances status

282
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

282
: Unemployment, unspecified

282
: Other problems related to housing and economic circumstances

283
: Allergy status to sulfonamides status

286
: Encounter for palliative care

286
: Home accidents

286
: Do not resuscitate status

287
: Unspecified place or not applicable

288
: Do not resuscitate status

288
: Long-term (current) use of aspirin

288
: Long-term (current) use of insulin

290
: Accidents occurring in unspecified place

293
: Do not resuscitate status

295
: Patient room in hospital as the place of occurrence of the external cause

295
: Unspecified place or not applicable

296
: Family history of ischemic heart disease and other diseases of the circulatory system

296
: Unspecified place in hospital as the place of occurrence of the external cause

299
: Do not resuscitate

299
: Encounter for palliative care

299
: Physical restraint status

300
: Physical restraints status

301
: Coma scale, eyes open, to pain, at arrival to emergency department

301
: Coma scale, best verbal response, none, at arrival to emergency department

301
: Encounter for palliative care

301
: Coma scale, best motor response, flexion withdrawal, at arrival to emergency department

301
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

305
: Patient room in hospital as the place of occurrence of the external cause

308
: Long term (current) use of insulin

308
: Patient's other noncompliance with medication regimen

308
: History of falling

311
: Need for prophylactic vaccination and inoculation against influenza

312
: Do not resuscitate status

316
: Other place in hospital as the place of occurrence of the external cause

316
: Do not resuscitate

319
: Long-term (current) use of insulin

319
: Personal history of tobacco use

325
: Examination of participant in clinical trial

326
: Do not resuscitate

326
: Unspecified place or not applicable

329
: Encounter for palliative care

329
: Do not resuscitate

329
: Encounter for adjustment and management of automatic implantable cardiac defibrillator

329
: Family history of ischemic heart disease and other diseases of the circulatory system

329
: Long term (current) use of anticoagulants

329
: Long term (current) use of insulin

329
: Personal history of nicotine dependence

332
: Physical restraint status

332
: Encounter for examination for normal comparison and control in clinical research program

333
: Examination of participant in clinical trial

334
: Encounter for immunization

334
: Unspecified place in hospital as the place of occurrence of the external cause

336
: Do not resuscitate

336
: Unspecified place in hospital as the place of occurrence of the external cause

336
: Unspecified place or not applicable

338
: Examination of participant in clinical trial

338
: Procedure not carried out for other reasons

340
: Do not resuscitate

342
: Do not resuscitate

342
: Encounter for adjustment and management of other part of cardiac pacemaker

342
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

346
: Lack of housing

347
: Encounter for palliative care

347
: Long term (current) use of antithrombotics/antiplatelets

355
: Unspecified place or not applicable

356
: Examination of participant in clinical trial

361
: Lack of housing

363
: Unspecified place in hospital as the place of occurrence of the external cause

366
: Bedroom of single-family (private) house as the place of occurrence of the external cause

368
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

369
: Do not resuscitate

380
: Kitchen in apartment as the place of occurrence of the external cause

386
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

387
: Do not resuscitate

389
: Lack of housing

395
: Unspecified place or not applicable

397
: Unspecified place or not applicable

399
: Encounter for immunization

402
: Outcome of delivery, single liveborn

415
: Encounter for immunization

418
: Encounter for immunization

418
: Car as the place of occurrence of the external cause

422
: Lack of housing

435
: Family history of ischemic heart disease and other diseases of the circulatory system

439
: Encounter for palliative care

439
: Do not resuscitate status

439
: Body Mass Index between 19-24, adult

440
: Unspecified place or not applicable

441
: Need for prophylactic vaccination and inoculation against streptococcus pneumoniae [pneumococcus] and influenza

444
: Unspecified place or not applicable

444
: Encounter for examination for normal comparison and control in clinical research program

453
: Long term (current) use of oral hypoglycemic drugs

454
: Need for prophylactic vaccination and inoculation against influenza

454
: Do not resuscitate status

454
: Body Mass Index between 19-24, adult

454
: Bed confinement status

454
: Personal history of tobacco use

454
: Long-term (current) use of aspirin

455
: Do not resuscitate

455
: Patient's other noncompliance with medication regimen

457
: Family history of diabetes mellitus

457
: Family history of ischemic heart disease

457
: Do not resuscitate status

459
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

460
: Examination of participant in clinical trial

461
: Unspecified place or not applicable

461
: Unspecified place in nursing home as the place of occurrence of the external cause

465
: Physical restraints status

465
: Accidents occurring in residential institution

474
: Do not resuscitate status

482
: Do not resuscitate status

484
: Encounter for immunization

485
: Long term (current) use of aspirin

491
: Personal history of noncompliance with medical treatment, presenting hazards to health

491
: Unemployment

492
: Do not resuscitate status

493
: Long-term (current) use of aspirin

493
: Encounter for palliative care

493
: Do not resuscitate status

493
: Physical restraints status

494
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

497
: Encounter for examination for normal comparison and control in clinical research program

498
: Examination of participant in clinical trial

498
: Accidents occurring in residential institution

502
: Personal history of nicotine dependence

503
: Unspecified place in hospital as the place of occurrence of the external cause

503
: Patient room in hospital as the place of occurrence of the external cause

506
: Lack of housing

508
: Operating room of hospital as the place of occurrence of the external cause

509
: Operating room of hospital as the place of occurrence of the external cause

509
: Encounter for examination for normal comparison and control in clinical research program

510
: Physical restraints status

510
: Home accidents

521
: Encounter for examination for normal comparison and control in clinical research program

528
: Unspecified place or not applicable

531
: Examination of participant in clinical trial

532
: Long-term (current) use of insulin

532
: Personal history of noncompliance with medical treatment, presenting hazards to health

537
: Long-term (current) use of aspirin

537
: Long-term (current) use of anticoagulants

537
: Accidents occurring in residential institution

539
: Unspecified place in hospital as the place of occurrence of the external cause

541
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

543
: Encounter for palliative care

543
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

544
: Physical restraint status

546
: Do not resuscitate status

548
: Do not resuscitate status

552
: Encounter for examination for normal comparison and control in clinical research program

555
: Examination of participant in clinical trial

556
: Examination of participant in clinical trial

562
: Unspecified place in hospital as the place of occurrence of the external cause

564
: Examination of participant in clinical trial

567
: Surgical or other procedure not carried out because of contraindication

567
: Encounter for therapeutic drug monitoring

569
: Encounter for examination for normal comparison and control in clinical research program

570
: Unspecified place in hospital as the place of occurrence of the external cause

572
: Dietary counseling and surveillance

575
: Do not resuscitate status

576
: Other place in hospital as the place of occurrence of the external cause

579
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

581
: Examination of participant in clinical trial

581
: Accidents occurring in residential institution

582
: Homelessness

586
: Unspecified place in nursing home as the place of occurrence of the external cause

587
: Accidental fall on or from other stairs or steps

587
: Home accidents

588
: Do not resuscitate

595
: Do not resuscitate status

597
: Encounter for palliative care

597
: Unspecified place or not applicable

602
: Fall on and from ladder, initial encounter

602
: Unspecified place or not applicable

605
: Do not resuscitate status

605
: Accidents occurring in residential institution

606
: Pedal cycle accident injuring pedal cyclist

607
: Laparoscopic surgical procedure converted to open procedure

609
: Examination of participant in clinical trial

609
: Other specified vaccinations against streptococcus pneumoniae [pneumococcus]

612
: Personal history of tobacco use

616
: Lack of housing

617
: Unspecified place in hospital as the place of occurrence of the external cause

622
: Family history of ischemic heart disease and other diseases of the circulatory system

622
: Family history of stroke

622
: Encounter for adjustment and management of other part of cardiac pacemaker

623
: Unspecified place or not applicable

627
: Unspecified place or not applicable

628
: Observation and evaluation for other specified suspected conditions

629
: Do not resuscitate

631
: Fall on same level from slipping, tripping and stumbling without subsequent striking against object, initial encounter

631
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

631
: Patient room in hospital as the place of occurrence of the external cause

634
: Homelessness

642
: Encounter for immunization

642
: Long term (current) use of antithrombotics/antiplatelets

642
: Presence of coronary angioplasty implant and graft

642
: Presence of automatic (implantable) cardiac defibrillator

642
: Family history of ischemic heart disease and other diseases of the circulatory system

650
: Unspecified place or not applicable

654
: Do not resuscitate

662
: Do not resuscitate

662
: Encounter for palliative care

669
: Procedure and treatment not carried out because of patient's decision for other reasons

677
: Knee joint replacement

680
: Long term (current) use of insulin

681
: Do not resuscitate status

682
: Patient room in hospital as the place of occurrence of the external cause

692
: Do not resuscitate

692
: Long term (current) use of antithrombotics/antiplatelets

692
: Long term (current) use of insulin

694
: Dependence on wheelchair

694
: Patient room in hospital as the place of occurrence of the external cause

694
: Do not resuscitate

696
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

698
: Unspecified place or not applicable

699
: Examination of participant in clinical trial

699
: Physical restraints status

699
: Accidents occurring in residential institution

700
: Long term (current) use of insulin

705
: Long term (current) use of insulin

708
: Personal history of antineoplastic chemotherapy

711
: Encounter for examination for normal comparison and control in clinical research program

711
: Unspecified place in hospital as the place of occurrence of the external cause

712
: Family history of asthma and other chronic lower respiratory diseases

712
: Family history of diabetes mellitus

713
: Long-term (current) use of insulin

714
: Laparoscopic surgical procedure converted to open procedure

717
: Unspecified place in apartment as the place of occurrence of the external cause

722
: Do not resuscitate

724
: Do not resuscitate status

725
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

726

In [9]:
evalturbo = analysis(evalturbo)

0
: Long-term (current) use of aspirin

14
: Unspecified place or not applicable

37
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

38
: Patient room in hospital as the place of occurrence of the external cause

47
: Other place in hospital as the place of occurrence of the external cause

72
: Unspecified place or not applicable

88
: Examination of participant in clinical trial

102
: Examination of participant in clinical trial

105
: Personal history of antineoplastic chemotherapy

105
: Personal history of tobacco use

105
: Do not resuscitate status

105
: Encounter for palliative care

108
: Osteoarthrosis, localized, not specified whether primary or secondary, site unspecified

108
: Do not resuscitate status

108
: Long-term (current) use of steroids

108
: Long-term (current) use of aspirin

108
: Physical restraints status

137
: Do not resuscitate

182
: Personal history of tobacco use

185
: Do not resuscitate

194
: Do not resuscitate

194
: Unspecified place or not applicable

211
: Accidental fall from ladder

213
: Unspecified place in apartment as the place of occurrence of the external cause

221
: Unspecified place or not applicable

222
: Do not resuscitate status

230
: Other motor vehicle traffic accident involving collision with motor vehicle injuring passenger in motor vehicle other than motorcycle

239
: Do not resuscitate

249
: Unspecified place or not applicable

262
: Encounter for immunization

268
: Unspecified place in hospital as the place of occurrence of the external cause

274
: Examination of participant in clinical trial

274
: Knee joint replacement

274
: Long-term (current) use of aspirin

274
: Long-term (current) use of antiplatelet/antithrombotic

274
: Personal history of tobacco use

274
: Long-term (current) use of insulin

276
: Patient room in hospital as the place of occurrence of the external cause

283
: Long term (current) use of anticoagulants

287
: Unspecified place or not applicable

290
: Accidents occurring in unspecified place

291
: Posttraumatic stress disorder

298
: Physical restraints status

300
: Physical restraints status

301
: Encounter for palliative care

302
: Body Mass Index 32.0-32.9, adult

305
: Patient room in hospital as the place of occurrence of the external cause

312
: Do not resuscitate status

321
: Personal history of tobacco use

333
: Examination of participant in clinical trial

334
: Encounter for immunization

334
: Presence of artificial hip joint, bilateral

334
: Unspecified place in hospital as the place of occurrence of the external cause

365
: History of fall

369
: Do not resuscitate

370
: Personal history of tobacco use

372
: Gastrostomy status

380
: Kitchen in apartment as the place of occurrence of the external cause

386
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

387
: Do not resuscitate

397
: Unspecified place or not applicable

438
: Fall from other slipping, tripping, or stumbling

444
: Unspecified place or not applicable

444
: Encounter for examination for normal comparison and control in clinical research program

457
: Do not resuscitate status

491
: Cocaine abuse, unspecified

491
: Personal history of noncompliance with medical treatment, presenting hazards to health

491
: Unemployment

491
: Tobacco use disorder

509
: Operating room of hospital as the place of occurrence of the external cause

509
: Encounter for examination for normal comparison and control in clinical research program

528
: Unspecified place or not applicable

529
: Family history of ischemic heart disease

530
: Unspecified fall

531
: Examination of participant in clinical trial

539
: Unspecified place in hospital as the place of occurrence of the external cause

546
: Do not resuscitate status

561
: Need for prophylactic vaccination and inoculation against streptococcus pneumoniae [pneumococcus] and influenza

564
: Examination of participant in clinical trial

567
: Surgical or other procedure not carried out because of contraindication

567
: Encounter for therapeutic drug monitoring

569
: Encounter for examination for normal comparison and control in clinical research program

570
: Unspecified place in hospital as the place of occurrence of the external cause

572
: Dietary counseling and surveillance

575
: Do not resuscitate status

576
: Other place in hospital as the place of occurrence of the external cause

587
: Home accidents

588
: Do not resuscitate

602
: Unspecified place or not applicable

606
: Pedal cycle accident injuring pedal cyclist

617
: Unspecified place in hospital as the place of occurrence of the external cause

627
: Unspecified place or not applicable

628
: Observation and evaluation for other specified suspected conditions

650
: Unspecified place or not applicable

654
: Do not resuscitate

662
: Do not resuscitate

662
: Encounter for palliative care

692
: Do not resuscitate

694
: Patient room in hospital as the place of occurrence of the external cause

694
: Do not resuscitate

696
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

698
: Unspecified place or not applicable

711
: Encounter for examination for normal comparison and control in clinical research program

711
: Unspecified place in hospital as the place of occurrence of the external cause

717
: Unspecified place in apartment as the place of occurrence of the external cause

722
: Do not resuscitate

725
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

729
: Operating room of hospital as the place of occurrence of the external cause

734
: Encounter for palliative care

734
: Do not resuscitate status

734
: Accidents occurring in residential institution

739
: Unspecified place or not applicable

759
: Unspecified place in hospital as the place of occurrence of the external cause

770
: Do not resuscitate

770
: Unspecified place or not applicable

779
: Do not resuscitate status

790
: Unspecified place or not applicable

821
: Unspecified place or not applicable

823
: Patient's other noncompliance with medication regimen

823
: Unspecified place in hospital as the place of occurrence of the external cause

832
: Encounter for examination for normal comparison and control in clinical research program

845
: Physical restraint status

851
: Unspecified place or not applicable

855
: Do not resuscitate

868
: Family history of malignant neoplasm of gastrointestinal tract

868
: Family history of malignant neoplasm of trachea, bronchus, and lung

884
: Do not resuscitate status

888
: Physical restraint status

888
: Patient's other noncompliance with medication regimen

898
: Unspecified place in hospital as the place of occurrence of the external cause

901
: Other specified places as the place of occurrence of the external cause

904
: Examination of participant in clinical trial

904
: Long-term (current) use of aspirin

904
: Need for prophylactic vaccination and inoculation against influenza

905
: Encounter for palliative care

905
: Home accidents

918
: Do not resuscitate status

918
: Encounter for palliative care

919
: Encounter for examination for normal comparison and control in clinical research program

929
: Examination of participant in clinical trial

929
: Accidents occurring in residential institution

935
: Do not resuscitate status

935
: Encounter for palliative care

937
: Unspecified place or not applicable

942
: Do not resuscitate

942
: Encounter for palliative care

952
: Do not resuscitate

952
: Tobacco use

954
: Encounter for palliative care

958
: Motor vehicle traffic accident due to loss of control, without collision on the highway, injuring motorcyclist

969
: Unspecified place in unspecified non-institutional (private) residence as the place of occurrence of the external cause

986
: Patient's other noncompliance with medication regimen

989
: Examination of participant in clinical trial

0.9968074136918358
0.9976538780016561

In [11]:
#merge and find the patients with differences in no_noninferables, order by highest number of diffs to lowest

In [24]:
evalturbo.columns

Index(['hadm_id', 'diagnoses', 'GPT_input', 'GPT-Diagnoses', 'GPT-Eval',
       'no_hits', 'no_noninferables', 'no_mistakes', 'no_excluded', 'hits',
       'noninferables', 'mistakes', 'excluded', 'total_ICD_diagnoses', 'error',
       'sensitivity'],
      dtype='object')

In [30]:
evalturbo['diagnoses']

0      1:Coronary atherosclerosis of native coronary ...
1      1:Sepsis, unspecified organism\r\n2:Other panc...
2      1:Mitral valve disorders\r\n2:Rupture of chord...
3      1:Benign neoplasm of ovary\r\n2:Pulmonary coll...
4      1:Atrioventricular block, complete\r\n2:Chroni...
                             ...
995    1:Other chest pain\r\n2:Atherosclerotic heart ...
996    1:Pneumonia, organism unspecified\r\n2:Acute p...
997    1:Coronary atherosclerosis of native coronary ...
998    1:Pneumonia, organism unspecified\r\n2:Liver r...
999    1:Acquired hypertrophic pyloric stenosis\r\n2:...
Name: diagnoses, Length: 1000, dtype: object

In [46]:
evalturbo['diagnoses'] = evalturbo['diagnoses'].str.replace('\r', '', regex=False)
eval41['diagnoses'] = eval41['diagnoses'].str.replace('\r', '', regex=False)

evalturbo['GPT_input'] = evalturbo['GPT_input'].str.replace('\r', '', regex=False)
eval41['GPT_input'] = eval41['GPT_input'].str.replace('\r', '', regex=False)

In [47]:
merged = evalturbo.merge(eval41, how='outer', on=['hadm_id', 'diagnoses', 'GPT_input'], suffixes=('_turbo', '_41'))

In [49]:
merged['no_noninferables_diff'] =  merged['no_noninferables_41'] - merged['no_noninferables_turbo']

In [50]:
merged = merged.sort_values(by='no_noninferables_diff', ascending=False)

In [51]:
merged[['noninferables_turbo', 'noninferables_41']]

,noninferables_turbo,noninferables_41
352,,2; 6; 7; 8; 9; 10; 11; 14; 16; 19; 22; 23; 24;...
819,,4; 8; 11; 13; 14; 15; 16; 17; 18; 20; 21; 22; ...
558,12; 15; 17; 18; 21,1; 3; 4; 5; 6; 7; 8; 9; 10; 12; 14; 15; 17; 18...
60,,1; 7; 9; 10; 12; 13; 14; 15; 16; 18; 19
189,9; 10; 15,2; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16
...,...,...
687,5; 8; 9; 10; 16; 17; 18; 19; 20; 21,5; 8; 16; 17
275,1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14;...,1; 2; 3; 4; 5; 6; 7; 9; 13; 14; 15; 16; 17; 18...
843,1; 3; 5; 7; 8; 9; 11; 12; 13; 14; 16; 17; 18; ...,1; 3; 5; 7; 11; 15; 16; 19; 20
575,2; 6; 10; 11; 12; 14; 15; 16,2
465,6; 8; 11; 12; 13; 14; 15; 16; 17; 18; 19; 21; ...,6; 8; 10; 11; 16; 19; 21; 22; 25; 26; 28; 29

In [52]:
merged.columns

Index(['hadm_id', 'diagnoses', 'GPT_input', 'GPT-Diagnoses_turbo',
       'GPT-Eval_turbo', 'no_hits_turbo', 'no_noninferables_turbo',
       'no_mistakes_turbo', 'no_excluded_turbo', 'hits_turbo',
       'noninferables_turbo', 'mistakes_turbo', 'excluded_turbo',
       'total_ICD_diagnoses_turbo', 'error_turbo', 'sensitivity_turbo',
       'GPT-Diagnoses_41', 'GPT-Eval_41', 'no_hits_41', 'no_noninferables_41',
       'no_mistakes_41', 'no_excluded_41', 'hits_41', 'noninferables_41',
       'mistakes_41', 'excluded_41', 'total_ICD_diagnoses_41', 'error_41',
       'sensitivity_41', 'no_noninferables_diff'],
      dtype='object')

In [54]:
# prompt: in merged you have two columns that only contain numbers separated by ;
# 1. noninferables_turbo
# 2. noninferables_41
# Make them into sets of integers, remove the intersection from noninferables_41 to make it a column called noninferables_41_only and use it to index the column called diagnoses -> the diagnoses that correspond to those indices should be printed in column noninferable_diagnoses_41_only

merged['noninferables_turbo_set'] = merged['noninferables_turbo'].apply(lambda x: set(map(int, x.split('; '))) if isinstance(x, str) and x != '' else set())
merged['noninferables_41_set'] = merged['noninferables_41'].apply(lambda x: set(map(int, x.split('; '))) if isinstance(x, str) and x != '' else set())

merged['noninferables_41_only'] = merged.apply(lambda row: list(row['noninferables_41_set'] - row['noninferables_turbo_set']), axis=1)

def get_diagnoses_from_indices(diagnoses_str, indices_list):
    if not isinstance(diagnoses_str, str):
        return ""
    diagnoses_list = diagnoses_str.split('\n')
    selected_diagnoses = []
    for index in indices_list:
        # Adjust index for 0-based list if needed, assuming diagnosis numbers are 1-based
        list_index = index - 1
        if 0 <= list_index < len(diagnoses_list):
            selected_diagnoses.append(diagnoses_list[list_index].strip())
    return '; '.join(selected_diagnoses)

merged['noninferable_diagnoses_41_only'] = merged.apply(lambda row: get_diagnoses_from_indices(row['diagnoses'], row['noninferables_41_only']), axis=1)

In [58]:
merged[['GPT_input', 'noninferables_41_only', 'noninferable_diagnoses_41_only']]

,GPT_input,noninferables_41_only,noninferable_diagnoses_41_only
352,Blood report: \nThe patient stayed in the hosp...,"[2, 6, 7, 8, 9, 10, 11, 14, 16, 19, 22, 23, 24...",2:Other encephalopathy; 6:Stricture and stenos...
819,Blood report: \nThe patient stayed in the hosp...,"[4, 8, 11, 13, 14, 15, 16, 17, 18, 20, 21, 22,...",4:Hyperosmolality and/or hypernatremia; 8:Deli...
558,Blood report: \nThe patient stayed in the hosp...,"[1, 3, 4, 5, 6, 7, 8, 9, 10, 14, 20, 22]",1:Acute and subacute hepatic failure without c...
60,Blood report: \nThe patient stayed in the hosp...,"[1, 7, 9, 10, 12, 13, 14, 15, 16, 18, 19]","1:Fever, unspecified; 7:Displaced bicondylar f..."
189,Blood report: \nThe patient stayed in the hosp...,"[2, 4, 5, 6, 7, 8, 11, 12, 13, 14, 16]",2:Chronic systolic (congestive) heart failure;...
...,...,...,...
687,Blood report: \nThe patient stayed in the hosp...,[],
275,Blood report: \nThe patient stayed in the hosp...,[],
843,Blood report: \nThe patient stayed in the hosp...,[15],15:Unspecified viral hepatitis C without hepat...
575,Blood report: \nThe patient stayed in the hosp...,[],
465,Blood report: \nThe patient stayed in the hosp...,[10],"10:Nausea with vomiting, unspecified"

In [124]:
# prompt: # prompt: in merged you have two columns that only contain numbers separated by ;
# # 1. hits_turbo
# # 2. noninferables_41
# Make them into sets of integers, find the intersection (put it in a column called hits_turbo_noninferables_41_intersect and use this to index the column called diagnoses -> the diagnoses that correspond to those indices should be printed in column intersect_diags

merged['hits_turbo_set'] = merged['hits_turbo'].apply(lambda x: set(map(int, x.split('; '))) if isinstance(x, str) and x != '' else set())

merged['hits_turbo_noninferables_41_intersect'] = merged.apply(lambda row: list(row['hits_turbo_set'].intersection(row['noninferables_41_set'])), axis=1)

merged['intersect_diags'] = merged.apply(lambda row: get_diagnoses_from_indices(row['diagnoses'], row['hits_turbo_noninferables_41_intersect']), axis=1)

# Display the relevant columns
merged[['hadm_id', 'hits_turbo_noninferables_41_intersect', 'intersect_diags']].head(20)

,hadm_id,hits_turbo_noninferables_41_intersect,intersect_diags
352,23685637,"[2, 6, 7, 8, 9, 10, 11, 14, 16, 19, 22, 23, 24, 25, 26, 27, 28, 29]","2:Other encephalopathy; 6:Stricture and stenosis of esophagus; 7:Chronic systolic heart failure; 8:Acidosis; 9:Unspecified protein-calorie malnutrition; 10:Stridor; 11:Dysphagia, unspecified; 14:Malignant neoplasm of bladder, part unspecified; 16:Malignant neoplasm of prostate; 19:Congestive heart failure, unspecified; 22:Hypertensive chronic kidney disease, unspecified, with chronic kidney disease stage I through stage IV, or unspecified; 23:Chronic kidney disease, unspecified; 24:Stricture or kinking of ureter; 25:Hematuria, unspecified; 26:Iron deficiency anemia secondary to blood loss (chronic); 27:Altered mental status; 28:Diarrhea; 29:Other drugs and medicinal substances causing adverse effects in therapeutic use"
819,28339862,"[4, 8, 11, 13, 15, 16, 17, 18, 20, 21, 22, 26, 27]","4:Hyperosmolality and/or hypernatremia; 8:Delirium due to conditions classified elsewhere; 11:Chronic airway obstruction, not elsewhere classified; 13:Personal history of transient ischemic attack (TIA), and cerebral infarction without residual deficits; 15:Personal history of malignant neoplasm of bronchus and lung; 16:Acquired absence of organ, lung; 17:Dementia, unspecified, without behavioral disturbance; 18:Coronary atherosclerosis of native coronary artery; 20:Pure hypercholesterolemia; 21:Unspecified essential hypertension; 22:Personal history of tobacco use; 26:Peripheral vascular disease, unspecified; 27:Esophageal reflux"
558,25805325,"[1, 3, 4, 5, 6, 7, 8, 9, 10, 14, 20, 22]","1:Acute and subacute hepatic failure without coma; 3:Toxic encephalopathy; 4:Liver transplant failure; 5:Nephrotic syndrome with focal and segmental glomerular lesions; 6:Malignant neoplasm associated with transplanted organ; 7:Post-transplant lymphoproliferative disorder (PTLD); 8:Diffuse large B-cell lymphoma, lymph nodes of multiple sites; 9:Other complications of liver transplant; 10:Hepatic failure, unspecified without coma; 14:Essential (primary) hypertension; 20:Other cirrhosis of liver; 22:Sequelae of viral hepatitis"
60,20760364,"[1, 7, 9, 10, 12, 13, 14, 15, 16, 18, 19]","1:Fever, unspecified; 7:Displaced bicondylar fracture of right tibia, initial encounter for closed fracture; 9:Chronic systolic (congestive) heart failure; 10:Fall from chair, initial encounter; 12:Dependence on renal dialysis; 13:Long term (current) use of insulin; 14:Ischemic cardiomyopathy; 15:Atherosclerotic heart disease of native coronary artery without angina pectoris; 16:Presence of aortocoronary bypass graft; 18:Hyperlipidemia, unspecified; 19:Obstructive sleep apnea (adult) (pediatric)"
189,22068465,"[2, 4, 5, 6, 7, 8, 11, 12, 13, 14, 16]","2:Chronic systolic (congestive) heart failure; 4:Personal history of nicotine dependence; 5:Atherosclerotic heart disease of native coronary artery without angina pectoris; 6:Presence of aortocoronary bypass graft; 7:Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene; 8:Hyperlipidemia, unspecified; 11:Other long term (current) drug therapy; 12:Long term (current) use of oral hypoglycemic drugs; 13:Long term (current) use of aspirin; 14:Hypertensive heart disease with heart failure; 16:Old myocardial infarction"
683,27092887,"[1, 2, 3, 7, 8, 10, 11, 12, 13, 14, 17]","1:Persistent atrial fibrillation; 2:Cardiac tamponade; 3:Acute pericarditis, unspecified; 7:Other sequelae of cerebral infarction; 8:Heteronymous bilateral field defects; 10:Hyperlipidemia, unspecified; 11:Personal history of nicotine dependence; 12:Family history of ischemic heart disease and other diseases of the circulatory system; 13:Long term (current) use of anticoagulants; 14:Unspecified atrial flutter; 17:Ataxia following cerebral infarction"
587,26038786,"[1, 3, 5, 7, 10, 13, 14, 15, 16, 17, 19]","1:Necrosis of amputation stump, left lower extremity; 3:Non-pressure chronic ulcer of right heel and midfoot with unspecified severity; 5:Atherosclerosis of native arteries of extremities with gangrene, right leg; 7:Chronic atrial fibrillation; 10:Atherosclerotic heart disease of native coronary artery without angina pectoris; 13:Presence of aortocoronary bypass graft; 14:Presence of xenogenic heart valve; 15:Acquired absence of other right toe(s); 16:Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease, or unspecified chronic kidney disease; 17:Chronic kidney disease, unspecified; 19:Non-pressure chronic ulcer of other part of right foot with unspecified severity"
182,21965472,"[2, 5, 6, 9, 10, 11, 12, 13, 14, 15, 19]","2:Acute on chronic diastolic heart failure; 5:Sinoatrial node dysfunction; 6:Congestive heart failure, unspecified; 9:Paroxysmal ventricular tachycardia; 10:Diabetes with neurological manifestations, type II or unspecified type, not stated as uncontrolled; 11:Polyneuropathy in diabetes; 12:Diabetes with renal manifestations, type II or unspecified type, not stated as uncontrolled; 13:Diabetes with ophthalmic manifestations, type II or unspecified type, not stated as uncontrolled; 14:Background diabetic retinopathy; 15:Chronic kidney disease, unspecified; 19:Hypertensive chronic kidney disease, benign, with chronic kidney disease stage I through stage IV, or unspecified"
262,22780338,"[3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 15]","3:Unspecified asthma with (acute) exacerbation; 4:Chronic diastolic (congestive) heart failure; 5:Body mass index (BMI) 40.0-44.9, adult; 7:Respiratory conditions due to unspecified external agent; 8:Dependence on supplemental oxygen; 9:Personal history of pulmonary embolism; 10:Long term (current) use of anticoagulants; 11:Personal history of other malignant neoplasm of large intestine; 12:Acute upper respiratory infection, unspecified; 13:Long term (current) use of insulin; 15:Morbid (severe) obesity due to excess calories"
821,28364772,"[1, 3, 8, 9, 10, 12, 14, 20, 21, 22]","1:Subendocardial infarction, initial episode of care; 3:Cardiogenic shock; 8:Other primary cardiomyopathies; 9:Other complications due to other cardiac device, implant, and graft; 10:Atrial flutter; 12:Atrial fibrillation; 14:Iron deficiency anemia secondary to blood loss (chronic); 20:Mitral valve disorders; 21:Diseases of tricuspid valve; 22:Other chronic pulmonary heart diseases"
761,27767280,"[2, 8, 13, 15, 16, 18, 19, 20, 21, 22]","2:Tumor lysis syndrome; 8:Secondary and unspecified malignant neoplasm of intra-abdominal lymph nodes; 13:Nonspecific low blood pressure reading; 15:Personal history of venous thrombosis and embolism; 16:Coronary atherosclerosis of unspecified type of vessel, native or graft; 18:Old myocardial infarction; 19:Atrial fibrillation; 20:Pure hypercholesterolemia; 21:Unspecified essential hypertension; 22:Personal history of tobacco use"
17,20334061,"[1, 2, 3, 8, 11, 12, 13, 17, 18, 19]","1:Longstanding persistent atrial fibrillation; 2:Pre-excitation syndrome; 3:Myocardial infarction type 2; 8:Atherosclerotic heart disease of native coronary artery without angina pectoris; 11:Other secondary hypertension; 12:Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene; 13:Hyperlipidemia, unspecified; 17:Long term (current) use of oral hypoglycemic drugs; 18:Personal history of nicotine dependence; 19:Presence of coronary angioplasty implant and graft"
824,28379893,"[2, 3, 5, 6, 7, 9, 10, 11, 17]","2:Acute kidney failure, unspecified; 3:Alcohol withdrawal; 5:Dehydration; 6:Cocaine abuse, unspecified; 7:Opioid abuse, unspecified; 9:Unspecified essential hypertension; 10:Cannabis abuse, unspecified; 11:Other and unspecified alcohol dependence, in remission; 17:Alcoholic gastritis, without mention of hemorrhage"
665,26933072,"[1, 2, 4, 6, 9, 12, 14, 15, 17]","1:Obstructive hypertrophic cardiomyopathy; 2:Cardiogenic shock; 4:Acidosis; 6:Hypovolemic shock; 9:Unspecified atrial fibrillation; 12:Urinary tract infection, site not specified; 14:Long term (current) use of anticoagulants; 15:Atherosclerotic heart disease of native coronary artery without angina pectoris; 17:Nonrheumatic mitral (valve) insufficiency"
299,23052982,"[1, 2, 4, 5, 6, 7, 12, 14, 15]","1:Atherosclerosis of native arteries of the extremities with rest pain; 2:Other arterial embolism and thrombosis of abdominal aorta; 4:Coronary atherosclerosis of unspecified type of vessel, native or graft; 5:Unspecified essential hypertension; 6:Other and unspecified hyperlipidemia; 7:Old myocardial infarction; 12:Personal history of transient ischemic attack (TIA), and cerebral infarction without residual deficits; 14:Cannabis abuse, unspecified; 15:Opioid abuse, unspecified"
818,28339391,"[2, 4, 5, 7, 8, 9, 10, 13, 18]","2:Obstruction of bile duct; 4:Chronic or unspecified duodenal ulcer with hemorrhage, without mention of obstruction; 5:Secondary malignant neoplasm of small intestine including duodenum; 7:Mechanical complication due to other implant and internal device, not elsewhere classified; 8:Cholangitis; 9:Malignant neoplasm of liver, secondary; 10:Malignant neoplasm of head of pancreas; 13:Surgical operation with implant of artificial internal device causing abnormal patient reaction, or later complication,without mention of misadventure at time of operation; 18:Fever presenting with conditions classified elsewhere"
519,25446716,"[1, 3, 8, 12, 13, 14, 15, 16, 19]","1:Ventricular tachycardia; 3:Ventricular fibrillation; 8:Dilated cardiomyopathy; 12:Type 2 diabetes mellitus with diabetic chronic kidney disease; 13:Atherosclerotic heart disease of native coronary artery without angina pectoris; 14:Chronic atrial fibrillation; 15:Iron deficiency anemia, unspecified; 16:Old myocardial infarction; 19:Presence of aortocoronary bypass graft"
279,22922413,"[1, 2, 34, 4, 10, 17, 18, 19, 24, 27]",1:Ventricular tachycardia; 2:Myocardial infarction type 2; 34:Long term (current) use of insulin; 4:Type 1 diabetes mellitus with ketoacidosis without coma; 10:Type 1 diabetes mellitus with diabetic autonomic (poly)neuropathy; 17:Type 1 diabetes mellitus with diabetic peripheral angiopathy without gangrene; 18:Ischemic cardiomyopathy; 19:Atherosclerotic heart disease of native coronary artery without angina pectoris; 24:Type 1 diabetes mellitus with unspecified diabetic retinopathy without macular edema; 27:Old myocardial infarction
733,27531305,"[2, 3, 5, 7, 8, 9, 13, 14, 15]","2:Delirium due to known physiological condition; 3:Chronic obstructive pulmonary disease, unspecified; 5:Atherosclerotic heart disease of native coronary artery without angina pectoris; 7:Presence of coronary angioplasty implant and graft; 8:Essential (primary) hypertension; 9:Hyperlipidemia, unspecified; 13:Obstructive sleep apnea (adult) (pediatric); 14:Obesity, unspecified; 15:Body mass index (BMI) 35.0-35.9, adult"
943,29554329,"[1, 5, 11, 12, 15, 18, 19, 21]","1:Disruption of external operation (surgical) wound, not elsewhere classified, initial encounter; 5:Atherosclerotic heart disease of native coronary artery without angina pectoris; 11:Hypertrophy of breast; 12:Old myocardial infarction; 15:Presence of aortocoronary bypass graft; 18:Long term (current) use of insulin; 19:Surgical operation with anastomosis, bypass or graft as the cause of abnormal reaction of the patient, or of later complication, without mention of misadventure at the time of the procedure; 21:Peripheral vascular angioplasty status with implants and grafts"

In [135]:
chosen_index = 262

In [136]:
merged.loc[chosen_index]['intersect_diags']

'3:Unspecified asthma with (acute) exacerbation; 4:Chronic diastolic (congestive) heart failure; 5:Body mass index (BMI) 40.0-44.9, adult; 7:Respiratory conditions due to unspecified external agent; 8:Dependence on supplemental oxygen; 9:Personal history of pulmonary embolism; 10:Long term (current) use of anticoagulants; 11:Personal history of other malignant neoplasm of large intestine; 12:Acute upper respiratory infection, unspecified; 13:Long term (current) use of insulin; 15:Morbid (severe) obesity due to excess calories'

In [137]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
print(merged.loc[chosen_index]['GPT-Eval_turbo'])

D1: Acute and chronic respiratory failure with hypercapnia
Question 1: No, this is similar to diagnosis *Chronic Type 2 Respiratory Failure (Hypercapnic Respiratory Failure)*
Question 2: N/A

D2: Interstitial pulmonary disease, unspecified
Question 1: No, this falls under the broader category of *Chronic Pulmonary Disease*
Question 2: N/A

D3: Unspecified asthma with (acute) exacerbation
Question 1: No, this could be considered as part of the differential diagnosis for *Chronic Pulmonary Disease*
Question 2: N/A

D4: Chronic diastolic (congestive) heart failure
Question 1: No, this could be related to *Chronic Pulmonary Disease* and *Metabolic Alkalosis (Compensated with Chronic Hypercapnia)* due to chronic congestion
Question 2: N/A

D5: Body mass index (BMI) 40.0-44.9, adult
Question 1: No, this is related to *Chronic Type 2 Respiratory Failure (Hypercapnic Respiratory Failure)* as severe obesity hypoventilation was considered
Question 2: N/A

D6: Acute and chronic respiratory failure with hypoxia
Question 1: No, this is similar to diagnosis *Chronic Type 2 Respiratory Failure (Hypercapnic Respiratory Failure)*
Question 2: N/A

D7: Respiratory conditions due to unspecified external agent
Question 1: No, this could be related to *Chronic Pulmonary Disease*
Question 2: N/A

D8: Dependence on supplemental oxygen
Question 1: No, this is a complication of *Chronic Type 2 Respiratory Failure (Hypercapnic Respiratory Failure)*
Question 2: N/A

D9: Personal history of pulmonary embolism
Question 1: No, this is a specific past medical history that could be related to *Chronic Pulmonary Disease*
Question 2: N/A

D10: Long term (current) use of anticoagulants
Question 1: No, this is related to the management of conditions such as *Personal history of pulmonary embolism*
Question 2: N/A

D11: Personal history of other malignant neoplasm of large intestine
Question 1: No, this is a specific past medical history that does not directly relate to the diagnoses listed but could have systemic effects
Question 2: N/A

D12: Acute upper respiratory infection, unspecified
Question 1: No, this could be related to *Chronic Pulmonary Disease* as an acute exacerbation
Question 2: N/A

D13: Long term (current) use of insulin
Question 1: No, this is related to the management of *Poor Glycaemic Control (Diabetes Mellitus, Uncontrolled)*
Question 2: N/A

D14: Other specified disorders of bone density and structure, unspecified site
Question 1: Yes
Question 2: No, there is no data provided in the initial query that would suggest bone density or structural disorders.

D15: Morbid (severe) obesity due to excess calories
Question 1: No, this is related to *Chronic Type 2 Respiratory Failure (Hypercapnic Respiratory Failure)* as severe obesity hypoventilation was considered
Question 2: N/A

D16: Type 2 diabetes mellitus with hyperglycemia
Question 1: No, this is similar to diagnosis *Poor Glycaemic Control (Diabetes Mellitus, Uncontrolled)*
Question 2: N/A

D17: Adverse effect of glucocorticoids and synthetic analogues, initial encounter
Question 1: Yes
Question 2: No, there is no data provided in the initial query that would suggest an adverse effect of medication.

D18: Unspecified place or not applicable
Question 1: No, this is not a medical diagnosis.
Question 2: N/A

In [138]:
print(merged.loc[chosen_index]['GPT-Eval_41'])

D1: Acute and chronic respiratory failure with hypercapnia
Question 1: No, this is the same as *Type 2 (hypercapnic) respiratory failure* in my initial list.
Question 2: N/A

D2: Interstitial pulmonary disease, unspecified
Question 1: No, this is covered under *Chronic or resolved lung disease/interstitial lung process* in my initial list.
Question 2: N/A

D3: Unspecified asthma with (acute) exacerbation
Question 1: Yes
Question 2: No, there is no mention of a history of asthma, wheeze, reversible airway obstruction, or bronchodilator response in the data provided. Additional data such as a history of asthma, clinical wheeze, or spirometry would have been helpful.

D4: Chronic diastolic (congestive) heart failure
Question 1: Yes
Question 2: No, there is no direct evidence of heart failure in the data provided. The chest x-ray mentions "accentuation of the heart size" and "perihilar and bibasilar opacities," which could be suggestive, but there is no mention of clinical signs (e.g., oedema, raised JVP), echocardiogram findings, or BNP levels. Additional data such as echocardiogram results, BNP/pro-BNP, or clinical signs of heart failure would have been helpful.

D5: Body mass index (BMI) 40.0-44.9, adult
Question 1: Yes
Question 2: No, BMI is not provided in the data. Height and weight or BMI value would have been needed.

D6: Acute and chronic respiratory failure with hypoxia
Question 1: No, this is part of *Type 2 (hypercapnic) respiratory failure* and is supported by the low pO2 in the blood gas.
Question 2: N/A

D7: Respiratory conditions due to unspecified external agent
Question 1: Yes
Question 2: No, there is no mention of exposure to an external agent in the data provided. Information about environmental or occupational exposures would have been helpful.

D8: Dependence on supplemental oxygen
Question 1: Yes
Question 2: No, there is no mention of oxygen therapy or requirement for supplemental oxygen in the data provided. Documentation of oxygen use would have been needed.

D9: Personal history of pulmonary embolism
Question 1: Yes
Question 2: No, there is no mention of a history of pulmonary embolism in the data provided. Past medical history or imaging confirming PE would have been needed.

D10: Long term (current) use of anticoagulants
Question 1: Yes
Question 2: No, there is no mention of anticoagulant use in the data provided. Medication history would have been needed.

D11: Personal history of other malignant neoplasm of large intestine
Question 1: Yes
Question 2: No, there is no mention of a history of large intestine malignancy in the data provided. Past medical history or oncology records would have been needed.

D12: Acute upper respiratory infection, unspecified
Question 1: Yes
Question 2: No, there is no mention of symptoms such as sore throat, cough, fever, or upper respiratory tract findings in the data provided. Clinical history or examination findings would have been needed.

D13: Long term (current) use of insulin
Question 1: Yes
Question 2: No, there is no mention of insulin use in the data provided. Medication history would have been needed.

D14: Other specified disorders of bone density and structure, unspecified site
Question 1: Yes
Question 2: No, there is no mention of bone density or structure disorders in the data provided. Bone density scan results or clinical diagnosis would have been needed.

D15: Morbid (severe) obesity due to excess calories
Question 1: Yes
Question 2: No, BMI or weight/height data is not provided. This would be required to establish the diagnosis.

D16: Type 2 diabetes mellitus with hyperglycemia
Question 1: No, this is covered under *Hyperglycaemia (consistent with diabetes mellitus)* in my initial list.
Question 2: N/A

D17: Adverse effect of glucocorticoids and synthetic analogues, initial encounter
Question 1: Yes
Question 2: No, there is no mention of glucocorticoid or steroid use, nor any adverse effects attributed to them in the data provided. Medication history and adverse event documentation would have been needed.

D18: Unspecified place or not applicable
Question 1: No, this is not a medical diagnosis.
Question 2: N/A

In [139]:
print(merged.loc[chosen_index]['GPT-Diagnoses_turbo'])

*Chronic Type 2 Respiratory Failure (Hypercapnic Respiratory Failure)*
- Venous blood gas: pH 7.36 (high-normal), pCO2 73 mmHg (markedly elevated), Total CO2 43 (elevated), base excess 11 (elevated)
- pO2 55 (hypoxaemia)
- Chronic compensation (normal-ish pH with elevated pCO2/base excess, consistent with chronicity)
- History of baseline dyspnoea, now acutely worsened
- Radiology: evidence of chronic cardiopulmonary changes (perihilar and basilar opacities, bronchovascular crowding, slightly reduced lung volumes)
- Clinical suspicion for underlying chronic lung disease or neuromuscular-structural disorder is high due to these features
- Alternative differentials to consider: severe obesity hypoventilation, neuromuscular disease, chest wall deformities

*Anaemia (Normocytic, Mild)*
- Minimum haemoglobin: 11 g/dL, maximum: 11.6 g/dL (below normal reference range)
- Haematocrit: minimum 35.6, maximum 38 (mildly reduced)
- MCV: normal range (89–90)
- RDW: 15.6–15.8 (mildly elevated), possible anisocytosis
- RBC: mildly reduced (min 3.95, max 4.26)
- MCH/MCHC: low-normal
- Platelets: normal
- Alternative differentials to consider: anaemia of chronic disease, early iron deficiency anaemia, mild haemolytic anaemia

*Poor Glycaemic Control (Diabetes Mellitus, Uncontrolled)*
- Minimum glucose: 179 mg/dL, maximum: 277 mg/dL, average: 228 mg/dL (all above diagnostic threshold for diabetes)
- No evidence of ketoacidosis (normal pH, no mention of ketones), no evidence of hyperosmolar coma from available data
- Alternative differentials to consider: stress hyperglycaemia, undiagnosed diabetes mellitus, steroid-induced hyperglycaemia

*Chronic Pulmonary Disease (e.g., Chronic Obstructive Pulmonary Disease, Interstitial Lung Disease)*
- Chronic perihilar and bibasilar opacities on chest imaging, unchanged from previous scan
- Baseline dyspnoea worsening
- Reduced lung volumes on imaging
- Absence of new consolidation, pleural effusion, or pneumothorax
- Bronchovascular crowding, accentuated heart size may suggest chronicity/congestion
- Alternative differentials to consider: pulmonary oedema (chronic congestive heart failure), interstitial lung disease, bronchiectasis

*Metabolic Alkalosis (Compensated with Chronic Hypercapnia)*
- Blood gas: base excess 11 (markedly elevated), total CO2 43 (elevated)
- Chloride: low-normal (min 91, max 94)
- Potassium: normal
- Chronic compensation for respiratory acidosis (very high CO2/very high base excess)
- Alternative differentials to consider: exogenous bicarbonate administration, diuretic use, vomiting/gastric losses